Repository Power-Rangers-3/Front-end, pull requests merged in 2023-03, with the labels that each got.

#79 Task #73 Admin page
  .eslintrc.json
  src/App.tsx
  src/assets/icons/dashboard-icon.svg
  src/assets/icons/exit.svg
  src/assets/images/avatar.jpg
  src/assets/index.ts
  src/components/MenuNavAdmin/MenuNavAdmin.tsx
  src/components/MenuNavAdmin/menuList.ts
  src/components/MenuNavAdmin/styles.module.scss
  src/components/index.ts
  src/index.tsx
  src/modules/Auth/api/userSignIn.ts
  src/modules/Profile/changeNameForm/changeNameForm.tsx
  src/modules/Profile/styles/styles.module.scss
  src/pages/AdminPage/AdminPageLayout/AdminPageLayout.tsx
  src/pages/AdminPage/AdminPageLayout/styles.module.scss
  src/pages/MainLayout/styles.module.scss
  src/router/ProtectedAdminPage.tsx
  src/router/router.tsx
  src/router/routes.ts
  src/store/actions/signInAction.ts
  src/store/features/userSlice.ts
  src/store/types/IUser.ts
  src/store/types/index.ts
  src/styles/globalStyles.ts
  src/styles/shared/variables.ts
Labels: Front, task

#80 Task#69 user dashboard
  src/pages/ProfileDashboardPage/ProfileDashboardPage.tsx
  src/pages/ProfileDashboardPage/styles.module.scss
  src/pages/ProfileLayout/ProfileLayout.tsx
  src/pages/ProfileLayout/styles.module.scss
  src/pages/ProfileSettingsPage/SettingsPage.tsx
  src/pages/ProfileSettingsPage/styles.module.scss
  src/pages/index.ts
  src/router/router.tsx
  src/router/routes.ts
  src/styles/globalStyles.ts
Labels: Front, task

#81 Task#69 Create HistoryPage and FavoritePage
  src/pages/ProfilePages/ProfileDashboardPage/ProfileDashboardPage.tsx
  src/pages/ProfilePages/ProfileDashboardPage/styles.module.scss
  src/pages/ProfilePages/ProfileFavoritePage/ProfileFavoritePage.tsx
  src/pages/ProfilePages/ProfileFavoritePage/styles.module.scss
  src/pages/ProfilePages/ProfileHistoryPage/ProfileHistoryPage.tsx
  src/pages/ProfilePages/ProfileHistoryPage/styles.module.scss
  src/pages/ProfilePages/ProfileSettingsPage/ProfileSettingsPage.tsx
  src/pages/ProfilePages/ProfileSettingsPage/styles.module.scss
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/styles.module.scss
  src/pages/index.ts
  src/router/router.tsx
  src/router/routes.ts
Labels: Front, subtask

#82 Task_71 PlatformPage
  package-lock.json
  src/components/MenuNav/MenuNav.tsx
  src/components/MenuNav/config/routes.ts
  src/modules/Auth/api/userSignIn.ts
  src/modules/Auth/types/index.ts
  src/modules/Auth/types/userResponse.ts
  src/pages/HomePage/components/mainSection/mainSection.tsx
  src/pages/HomePage/components/opportunitySection/opportunitySection.tsx
  src/pages/PlatformsPage/PlatformsPage.tsx
  src/pages/PlatformsPage/components/assets/AiMyLogic.png
  src/pages/PlatformsPage/components/assets/Artsend_.jpg
  src/pages/PlatformsPage/components/assets/BotHelp1.png
  src/pages/PlatformsPage/components/assets/Botmaker.png
  src/pages/PlatformsPage/components/assets/botkits_.png
  src/pages/PlatformsPage/components/assets/botsify.png
  src/pages/PlatformsPage/components/assets/businessbot.png
  src/pages/PlatformsPage/components/assets/favoriteIcon.svg
  src/pages/PlatformsPage/components/assets/photo.png
  src/pages/PlatformsPage/components/assets/sberbb.png
  src/pages/PlatformsPage/components/data/dataArray.ts
  src/pages/PlatformsPage/components/platformsSection.tsx
  src/pages/PlatformsPage/components/styles.module.scss
  src/pages/PlatformsPage/components/types/dataPlatformsType.ts
  src/pages/PlatformsPage/styles.module.scss
  src/pages/index.ts
  src/router/ProtectedAdminPage.tsx
  src/router/router.tsx
  src/router/routes.ts
  src/store/actions/signInAction.ts
  src/store/features/userSlice.ts
  src/store/types/index.ts
  src/store/types/user.ts
  tsconfig.json
Labels: Front, task

#84 #74 init: privateRoute task
  package-lock.json
  src/router/ProtectedRoute.tsx
  src/router/index.ts
Labels: Front, task

#86 #70: create visit history
  protected-routes/node_modules/yocto-queue/readme.md
  src/App.tsx
  src/assets/icons/exit.svg
  src/assets/icons/heart.svg
  src/assets/icons/profile.svg
  src/assets/icons/search.svg
  src/assets/icons/vertical-dots.svg
  src/assets/index.ts
  src/components/Header/Header.tsx
  src/components/MenuNav/MenuNav.tsx
  src/components/MenuNavAdmin/MenuNavAdmin.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/styles.module.scss
  src/components/PlatformCard/PlatformCard.tsx
  src/components/PlatformCard/styles.module.scss
  src/components/PlatformList/PlatformList.tsx
  src/components/Profile/Profile.tsx
  src/components/Profile/config/routes.ts
  src/components/Profile/styles.module.scss
  src/components/ProtectedAdmin/ProtectedAdmin.tsx
  src/components/index.ts
  src/index.tsx
  src/layouts/MainLayout/MainLayout.tsx
  src/layouts/ProfileLayout/ProfileLayout.tsx
  src/layouts/ProfileLayout/config/routes.ts
  src/layouts/ProfileLayout/styles.module.scss
  src/mocks/platforms/platforms.ts
  src/pages/PlatformDetailsPage/PlatformDetailsPage.tsx
  src/pages/PlatformsPage/PlatformsPage.tsx
  src/pages/ProfilePages/ProfileDashboardPage/styles.module.scss
  src/pages/ProfilePages/ProfileFavoritePage/ProfileFavoritePage.tsx
  src/pages/ProfilePages/ProfileFavoritePage/styles.module.scss
  src/pages/ProfilePages/ProfileHistoryPage/ProfileHistoryPage.tsx
  src/pages/ProfilePages/ProfileHistoryPage/styles.module.scss
  src/pages/ProfilePages/ProfilePlatforms/ProfilePlatforms.tsx
  src/pages/index.ts
  src/router/router.tsx
  src/router/routes.ts
  src/shared/localStorage/localStorage.ts
  src/store/features/platformSlice.ts
  src/store/features/platformsSlice.ts
  src/store/index.ts
  src/store/types/platform.ts
Labels: Front, task

#87 #19 fix: changed validation rules, refactor validation schemes
  .stylelintignore
  src/components/Pagination/styles.module.scss
  src/components/Profile/styles.module.scss
  src/modules/Auth/UI/Input/Input.tsx
  src/modules/Auth/data/emailScheme.ts
  src/modules/Auth/data/newPasswordScheme.ts
  src/modules/Auth/data/registrationScheme.ts
  src/modules/Auth/data/signInScheme.ts
  src/modules/Profile/data/changeNameScheme.ts
  src/modules/Profile/data/changePasswordScheme.ts
  src/pages/Auth/styles.module.scss
  src/pages/ProfilePages/ProfileDashboardPage/styles.module.scss
  src/pages/ProfilePages/ProfileHistoryPage/styles.module.scss
  src/shared/validationRules/regularExpressions.ts
  src/shared/validationRules/validationRules.ts
Labels: Front

#88 feat: create tabs component
  src/components/Loading/Loading.tsx
  src/components/Loading/styles.module.scss
  src/components/PlatformCard/styles.module.scss
  src/components/PlatformList/styles.module.scss
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/styles.module.scss
  src/components/index.ts
  src/mocks/platforms/platforms.ts
  src/pages/PlatformsPage/PlatformsPage.tsx
  src/pages/PlatformsPage/styles.module.scss
  src/store/actions/index.ts
  src/store/actions/sortPlatformsAction.ts
  src/store/selectors/platformsSelector.ts
  src/store/store.ts
  src/store/types/sortPlatform.ts
Labels: Front, task

#89 #70: fix visit history
  src/components/Loading/styles.module.scss
  src/components/PlatformCard/styles.module.scss
  src/components/Tabs/styles.module.scss
  src/modules/Profile/changePasswordForm/changePasswordForm.tsx
  src/modules/Profile/styles/styles.module.scss
  src/store/actions/index.ts
  src/store/actions/sortPlatformsAction.ts
  src/store/features/platformsSlice.ts
Labels: Front, bug

#90 Reset password via email #39-41
  src/components/ProtectedUnAuth/ProtectedUnAuth.tsx
  src/components/index.ts
  src/modules/Auth/NewPasswordForm/NewPasswordForm.tsx
  src/modules/Auth/RegistrationForm/RegistrationForm.tsx
  src/modules/Auth/ResetPassword/ResetPasswordForms.tsx
  src/modules/Auth/api/endpoints.ts
  src/modules/Auth/api/resetPassword.ts
  src/modules/Auth/api/sendEmail.ts
  src/modules/Auth/data/newPasswordScheme.ts
  src/modules/Auth/styles.module.scss
  src/modules/Auth/types/index.ts
  src/modules/Auth/types/newPasswordType.ts
  src/modules/Auth/types/resetPasswordType.ts
  src/modules/Auth/types/sendEmailType.ts
  src/pages/Auth/styles.module.scss
  src/router/router.tsx
  src/shared/validationRules/validationRules.ts
Labels: Front

#99 fix error messages #39-41
  src/modules/Auth/NewPasswordForm/NewPasswordForm.tsx
  src/modules/Auth/ResetPassword/ResetPasswordForms.tsx
Labels: Front
