Repository Power-Rangers-3/Front-end, pull requests merged in 2023-02, with the labels that each got.

#27 Change lint settings
  .eslintrc.json
  .stylelintrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.test.tsx
  src/Styles.module.css
  src/Styles.module.scss
Labels: Front

#29 Общие - создать глобальные стили#3
  .eslintrc.json
  package-lock.json
  package.json
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/styles.module.scss
  src/pages/MainLayout/MainLayout.tsx
  src/router/router.tsx
  src/store/features/themeSlice.ts
  src/store/features/userSlice.ts
  src/store/index.ts
  src/store/selectors/themeSelector.ts
  src/store/store.ts
  src/styles/globalStyles.ts
  src/styles/shared/breakpoints.ts
  src/styles/shared/fontWeight.ts
  src/styles/shared/variables.ts
Labels: Front, task

#31 Header
  package-lock.json
  package.json
  src/App.test.tsx
  src/Styles.module.css
  src/Styles.module.css.map
  src/assets/icons/logo.svg
  src/assets/index.ts
  src/components/Component/Component.tsx
  src/components/Header/Header.tsx
  src/components/Header/styles.module.css
  src/components/Header/styles.module.css.map
  src/components/Header/styles.module.scss
  src/components/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/styles.module.css
  src/pages/HomePage/styles.module.css.map
  src/pages/MainLayout/MainLayout.tsx
  src/store/selectors/userSelector.ts
  src/styles/globalStyles.ts
Labels: Front

#30 Registration form
  .eslintrc.json
  .example.env
  .gitignore
  .stylelintignore
  .stylelintrc
  package-lock.json
  package.json
  src/Styles.module.scss
  src/assets/index.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.module.css
  src/components/Header/styles.module.scss
  src/modules/RegistrationForm/UI/Input/Input.tsx
  src/modules/RegistrationForm/UI/Input/input.styles.module.css
  src/modules/RegistrationForm/UI/Input/input.styles.module.scss
  src/modules/RegistrationForm/UI/Input/input.type.ts
  src/modules/RegistrationForm/UI/buttonStyles/button.styles.module.css
  src/modules/RegistrationForm/UI/buttonStyles/button.styles.module.scss
  src/modules/RegistrationForm/api/UserRegistration.ts
  src/modules/RegistrationForm/assets/icons/eye-close.svg
  src/modules/RegistrationForm/assets/icons/eye-open.svg
  src/modules/RegistrationForm/assets/icons/facebook.svg
  src/modules/RegistrationForm/assets/icons/google.svg
  src/modules/RegistrationForm/assets/icons/mail.svg
  src/modules/RegistrationForm/assets/icons/vk.svg
  src/modules/RegistrationForm/assets/icons/warning.svg
  src/modules/RegistrationForm/assets/index.ts
  src/modules/RegistrationForm/data/registrationScheme.ts
  src/modules/RegistrationForm/data/regularExpressions.ts
  src/modules/RegistrationForm/registrationForm.styles.module.css
  src/modules/RegistrationForm/registrationForm.styles.module.scss
  src/modules/RegistrationForm/registrationForm.tsx
  src/modules/RegistrationForm/registrationForm.types.ts
  src/modules/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MainLayout/MainLayout.tsx
  src/pages/RegistrationPage/RegistrationPage.tsx
  src/router/router.tsx
  src/shared/fonts/Montserrat/Montserrat-Bold.ttf
  src/shared/fonts/Montserrat/Montserrat-BoldItalic.ttf
  src/shared/fonts/Montserrat/Montserrat-Italic.ttf
  src/shared/fonts/Montserrat/Montserrat-Medium.ttf
  src/shared/fonts/Montserrat/Montserrat-MediumItalic.ttf
  src/shared/fonts/Montserrat/Montserrat-Regular.ttf
  src/shared/fonts/Montserrat/Montserrat-SemiBold.ttf
  src/shared/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
  src/shared/fonts/fonts.css
  src/store/features/themeSlice.ts
  src/store/features/userSlice.ts
  src/store/index.ts
  src/store/selectors/themeSelector.ts
  src/store/selectors/userSelector.ts
  src/store/store.ts
  src/styles/globalStyles.ts
  src/styles/shared/variables.ts
Labels: Front, task

#34 Profile: create component
  .eslintrc.json
  src/components/Header/Header.tsx
  src/components/Header/styles.module.scss
  src/components/Profile/Profile.tsx
  src/components/Profile/styles.module.scss
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useToggle.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MainLayout/MainLayout.tsx
  src/store/features/userSlice.ts
Labels: Front, task

#36 Registration
  src/Styles.module.css
  src/Styles.module.css.map
  src/components/Header/styles.module.css
  src/components/Header/styles.module.scss
  src/modules/RegistrationForm/assets/icons/error.svg
  src/modules/RegistrationForm/assets/icons/user.svg
  src/modules/RegistrationForm/assets/index.ts
  src/modules/RegistrationForm/registrationForm.styles.module.css
  src/modules/RegistrationForm/registrationForm.styles.module.scss
  src/modules/RegistrationForm/registrationForm.tsx
  src/modules/RegistrationForm/types/registerUserType.ts
  src/modules/RegistrationForm/types/registrationErrorType.ts
  src/modules/RegistrationForm/utils/isFormFilled.ts
  src/styles/globalStyles.ts
Labels: Front, subtask

#38 Header adaptive
  .stylelintrc
  package-lock.json
  package.json
  public/index.html
  src/assets/icons/burger_menu.svg
  src/assets/icons/cancel.svg
  src/assets/images/girl.png
  src/assets/index.ts
  src/components/BurgerMenu/BurgerMenu.tsx
  src/components/BurgerMenu/styles.module.scss
  src/components/Footer/Styles.module.scss
  src/components/Header/Header.tsx
  src/components/Header/styles.module.css.map
  src/components/Header/styles.module.scss
  src/components/MenuNav/MenuNav.tsx
  src/components/MenuNav/styles.module.scss
  src/components/Portal/Portal.tsx
  src/components/Profile/styles.module.scss
  src/components/index.ts
  src/config/index.ts
  src/config/portal.ts
  src/hooks/index.ts
  src/hooks/useWindowSize.ts
  src/modules/Auth/RegistrationForm/RegistrationForm.tsx
  src/modules/Auth/api/index.ts
  src/modules/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/styles.module.css
  src/pages/HomePage/styles.module.css.map
  src/pages/HomePage/styles.module.scss
  src/pages/MainLayout/MainLayout.tsx
  src/pages/MainLayout/styles.module.css
  src/pages/MainLayout/styles.module.scss
  src/shared/fonts/fonts.css
  src/styles/shared/variables.ts
  src/types.d.ts
  tsconfig.json
Labels: Front

#62 feat: shared button styles, 1-3 sections of HomePage
  .stylelintignore
  src/components/MenuNav/MenuNav.tsx
  src/modules/Auth/api/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/components/advantagesSection/advantagesSection.tsx
  src/pages/HomePage/components/advantagesSection/assets/charm_tick.svg
  src/pages/HomePage/components/advantagesSection/assets/rocket_1.jpg
  src/pages/HomePage/components/advantagesSection/data/dataArray.ts
  src/pages/HomePage/components/advantagesSection/styles.advantagesSection.module.scss
  src/pages/HomePage/components/advantagesSection/types/dataAdvantagesType.ts
  src/pages/HomePage/components/mainSection/assets/blogging.jpg
  src/pages/HomePage/components/mainSection/assets/chat.svg
  src/pages/HomePage/components/mainSection/mainSection.tsx
  src/pages/HomePage/components/mainSection/styles.mainSection.module.scss
  src/pages/HomePage/components/opportunitySection/assets/analyse.jpg
  src/pages/HomePage/components/opportunitySection/assets/contact.jpg
  src/pages/HomePage/components/opportunitySection/assets/letters.jpg
  src/pages/HomePage/components/opportunitySection/assets/meditation.jpg
  src/pages/HomePage/components/opportunitySection/assets/time managment.jpg
  src/pages/HomePage/components/opportunitySection/data/dataArray.ts
  src/pages/HomePage/components/opportunitySection/opportunitySection.tsx
  src/pages/HomePage/components/opportunitySection/styles.opportunitySection.module.scss
  src/pages/HomePage/components/opportunitySection/types/dataOpportunityType.ts
  src/pages/HomePage/styles.module.scss
  src/styles/button.style.module.scss
Labels: Front

#64 fix: change registration form, fix logout
  src/components/MenuNav/MenuNav.tsx
  src/components/Profile/Profile.tsx
  src/modules/Auth/RegistrationForm/RegistrationForm.tsx
  src/modules/Auth/api/UserRegistration.ts
  src/modules/Auth/api/userSignIn.ts
  src/modules/Auth/data/registrationScheme.ts
  src/modules/Auth/types/registerUserType.ts
  src/router/router.tsx
  src/shared/localStorage/loalStorage.ts
  src/store/actions/signInAction.ts
  src/store/features/userSlice.ts
Labels: Front, subtask

#65 fix: fix registration
  src/modules/Auth/api/UserRegistration.ts
  src/modules/Auth/api/getToken.ts
Labels: Front, bug

#66 init: profileLayout and validate input
  package-lock.json
  package.json
  src/assets/icons/avatar.svg
  src/assets/icons/materials.svg
  src/assets/icons/my-history.svg
  src/assets/icons/my-page.svg
  src/assets/icons/rates.svg
  src/assets/icons/settings.svg
  src/assets/icons/uploaded.svg
  src/assets/icons/wallet.svg
  src/assets/index.ts
  src/components/BurgerMenu/styles.module.css
  src/components/BurgerMenu/styles.module.css.map
  src/components/BurgerMenu/styles.module.scss
  src/components/Header/styles.module.css
  src/components/Header/styles.module.scss
  src/components/MenuNav/styles.module.scss
  src/components/Profile/styles.module.css
  src/components/ProfileLayout/ProfileLayout.tsx
  src/components/ProfileLayout/styles.module.scss
  src/components/index.ts
  src/modules/Auth/UI/Input/input.styles.module.css
  src/modules/Auth/UI/Input/input.styles.module.css.map
  src/modules/Auth/UI/buttonStyles/button.styles.module.css
  src/modules/Auth/UI/buttonStyles/button.styles.module.css.map
  src/modules/Auth/data/ChangePassword/ChangePassword.ts
  src/modules/Auth/data/registrationScheme.ts
  src/modules/Auth/styles.module.css
  src/modules/Auth/styles.module.css.map
  src/modules/Auth/types/registerUserType.ts
  src/modules/index.ts
  src/pages/Auth/assets/icons/eye-close copy.svg
  src/pages/Auth/assets/icons/eye-open copy.svg
  src/pages/Auth/assets/icons/warning copy.svg
  src/pages/Auth/styles.module.css
  src/pages/Auth/styles.module.css.map
  src/pages/MainLayout/styles.module.css
  src/pages/SettingsPage/SettingsPage.tsx
  src/pages/SettingsPage/data/ChangePassword/ChangePassword.ts
  src/pages/SettingsPage/data/ChangePassword/UI/Input.tsx
  src/pages/SettingsPage/data/ChangePassword/UI/assets/eye-close.svg
  src/pages/SettingsPage/data/ChangePassword/UI/assets/eye-open.svg
  src/pages/SettingsPage/data/ChangePassword/UI/assets/index.ts
  src/pages/SettingsPage/data/ChangePassword/UI/assets/warning.svg
  src/pages/SettingsPage/data/ChangePassword/UI/input.ts
  src/pages/SettingsPage/data/ChangePassword/UI/styles.module.scss
  src/pages/SettingsPage/styles.module.scss
  src/pages/index.ts
  src/router/router.tsx
  src/router/routes.ts
  src/styles/shared/breakpoints.css
  src/styles/shared/breakpoints.css.map
Labels: Front

#76 Fix: styles landing page and refactor code
  package.json
  src/components/BurgerMenu/styles.module.scss
  src/components/Footer/Footer.tsx
  src/components/MenuNav/styles.module.scss
  src/modules/Auth/SignInForm/SignInForm.tsx
  src/modules/Profile/changeNameForm/changeNameForm.tsx
  src/modules/Profile/changePasswordForm/changePasswordForm.tsx
  src/pages/HomePage/components/advantagesSection/advantagesSection.tsx
  src/pages/HomePage/components/advantagesSection/styles.module.scss
  src/pages/HomePage/components/mainSection/mainSection.tsx
  src/pages/HomePage/components/mainSection/styles.module.scss
  src/pages/HomePage/components/opportunitySection/opportunitySection.tsx
  src/pages/HomePage/components/opportunitySection/styles.module.scss
  src/pages/HomePage/styles.module.scss
  src/pages/MainLayout/styles.module.scss
  src/pages/ProfileLayout/ProfileIcon/styles.module.scss
  src/pages/ProfileLayout/styles.module.scss
  src/pages/SettingsPage/SettingsPage.tsx
Labels: Front, subtask

#75 Fix: project imports
  .gitignore
  .idea/.gitignore
  .idea/Front-end.iml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/index.ts
  src/modules/Auth/index.ts
  src/modules/index.ts
  src/pages/Auth/NewPasswordPage/NewPasswordPage.tsx
  src/pages/Auth/RegistrationPage/RegistrationPage.tsx
  src/pages/Auth/ResetPasswordPage/ResetPasswordPage.tsx
  src/pages/Auth/SignInPage/SignInPage.tsx
  src/pages/index.ts
  src/router/router.tsx
  src/store/actions/signInAction.ts
Labels: Front, subtask

#77 Change password from profile
  src/components/Footer/Styles.module.scss
  src/modules/Auth/data/emailScheme.ts
  src/modules/Auth/data/registrationScheme.ts
  src/modules/Auth/data/signInScheme.ts
  src/modules/Profile/api/changePassword.ts
  src/modules/Profile/api/index.ts
  src/modules/Profile/api/userRename.ts
  src/modules/Profile/changeNameForm/changeNameForm.tsx
  src/modules/Profile/changePasswordForm/changePasswordForm.tsx
  src/modules/Profile/data/changeNameScheme.ts
  src/modules/Profile/data/changePasswordScheme.ts
  src/modules/Profile/data/index.ts
  src/modules/Profile/styles/styles.module.scss
  src/modules/Profile/types/changeNameType.ts
  src/modules/Profile/types/index.ts
Labels: Front
